### ISSUE TITLE
0.3.4 tagged release

### ISSUE THREAD

**Issue by jeffposnick** [googlearchive/polymer-test-tools#1]
There's currently no 0.3.4 tagged release to correspond to the latest Polymer release.

Not a big deal, but it seems like all the other repos under Polymer/\* have been tagged with a 0.3.4.

**Comment by ebidel** [comment]
@azakus is this part of your script?

**Comment by dfreedm** [comment]
No, I wasn't aware of this repo until just now.

**Comment by sorvell** [comment]
Addy, can you explain the purpose of this repo?

**Comment by ebidel** [comment]
We're starting to write tests for all the demos and elements in GWC, among others. It's so elements can depend on Polymer's testing harness without having to include their own copy directly.

**Comment by addyosmani** [comment]
@sorvell I asked @morethanreal to initially put this together as we've wanted to be able to consume the same testing setup the eng. team use as part of `seed-element`. We were previously including a manual copy (which made it hard to version/stay up to date).

**Comment by sorvell** [comment]
That sounds ok to me. Dan, let's make sure this gets tagged when we release. Sound ok?

**Comment by dfreedm** [comment]
This repo is now in the "automatic" release schedule, starting with 0.3.5
